version: '3.8'

services:
  backend:
    build: ./uat_tool
    ports:
      - "8005:8005"
    volumes:
      - ./uat_tool:/app
      - sqlite_data:/var/lib/sqlite
    environment:
      - DEBUG=1
      - DATABASE_URL=sqlite:////var/lib/sqlite/db.sqlite3
      - PYTHONPATH=/app
      - PATH=/opt/venv/bin:$PATH
    restart: unless-stopped
    networks:
      - appnet

  frontend:
    build: ./uat-frontend
    ports:
      - "5100:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_ALLOWED_HOSTS=uat.bitz-itc.com,localhost
    restart: unless-stopped
    networks:
      - appnet

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

volumes:
  sqlite_data:

networks:
  appnet:
